### ISSUE TITLE
Generates covers but 0 of 800 books can transfer to kindle

### ISSUE THREAD

**Issue by XabisMission** [weto91/kindle-cover-fixer#10]
Everything seems to work as described but once the app has generated covers the transfer to kindle button is greyed out

**Comment by weto91** [comment]
Hello, apparently it is the nominal work of the application.

The app will only enable the transfer to kindle button if any of the books in your Kindle library have the same UUID as the Caliber library books you've chosen.

If you've changed any details of the book in Caliber after you've transferred it to Kindle, the UUID of the book in Caliber will change, causing the app to detect that it's a different book. If this is your case, simply select all the books in Caliber, choose send to the device's main memory, and launch Kindle Cover Fixer again.

I hope I have been helpful!

**Comment by weto91** [comment]
Hello, did you solve the problem?

**Comment by XabisMission** [comment]
Hi,

I just tried again with 2.6 and it worked perfectly. Thank you so much for creating the app 🙂
________________________________

**Comment by weto91** [comment]
Hello! Perfect! I'm glad everything finally works!

All the best!
