### ISSUE TITLE
Doesn't work with new Kindles, e.g. Colorsoft 2024. The program immediately closes.

### ISSUE THREAD

**Issue by kailia** [weto91/kindle-cover-fixer#22]
Doesn't work with new Kindles, e.g. Colorsoft 2024. The program immediately closes.

**Comment by Darianna77** [comment]
Yeah...have that Problem too on the New Scribe :(
I hate that i dont have Covers and dont know how i can fix it now :/

**Comment by weto91** [comment]
Sorry, but i have not any new acribe to fix it, i only have the old one...
