### ISSUE TITLE
version 1.3 - Error handling null variable.

### ISSUE THREAD

**Issue by hideandseekstheorder** [weto91/kindle-cover-fixer#3]
![image](https://github.com/weto91/kindle-cover-fixer/assets/24226435/d4edbb3c-eb5b-4ea5-a619-a1b573eb7270)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Empty file name is not legal. (Parameter 'sourceFileName')
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at Kindle_Cover_Fixer.MainScreen.bookList(String action) in D:\Documents\PROYECTOS\VISUAL STUDIO\Kindle Cover Fixer\kindle-cover-fixer\Kindle Cover Fixer\Form1.cs:line 232
   at Kindle_Cover_Fixer.MainScreen.generateCoversButton_Click(Object sender, EventArgs e) in D:\Documents\PROYECTOS\VISUAL STUDIO\Kindle Cover Fixer\kindle-cover-fixer\Kindle Cover Fixer\Form1.cs:line 71
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Private.CoreLib.dll
----------------------------------------
Kindle Cover Fixer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Kindle%20Cover%20Fixer/Kindle%20Cover%20Fixer.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1823.27201
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1823.27201
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Collections.Specialized.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Collections.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/System.Drawing.Common.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    
    
![image](https://github.com/weto91/kindle-cover-fixer/assets/24226435/aacb76d9-da0e-4c4b-8fc4-4e8dd56579c6)

**Comment by hideandseekstheorder** [comment]
this run the app with Admin permissions or give correct permissions

**Comment by weto91** [comment]
Hello, I just uploaded version 2.4, which possibly also corrects this problem. Can you try it and tell me if it works for you now?

**Comment by hideandseekstheorder** [comment]
after i am update, the apps won't launch

**Comment by hideandseekstheorder** [comment]
![image](https://github.com/weto91/kindle-cover-fixer/assets/24226435/7722bef9-6c14-4e33-a6a1-c9b4cd25569c)
and launch when i am running it to windows 8 compatible, i am on windows 11 now,

**Comment by hideandseekstheorder** [comment]
i can't click calibre library icon folder

**Comment by hideandseekstheorder** [comment]
when click help, this happen 
![image](https://github.com/weto91/kindle-cover-fixer/assets/24226435/af3ab5ef-a863-484e-87bc-5a85bc937216)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not find file 'C:\WINDOWS\system32\help.rtf'.
File name: 'C:\WINDOWS\system32\help.rtf'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Windows.Forms.RichTextBox.LoadFile(String path, RichTextBoxStreamType fileType)
   at System.Windows.Forms.RichTextBox.LoadFile(String path)
   at Kindle_Cover_Fixer.HelpScreen.Form2_Load(Object sender, EventArgs e) in D:\Documents\PROYECTOS\VISUAL STUDIO\Kindle Cover Fixer\kindle-cover-fixer\Kindle Cover Fixer\Form2.cs:line 22
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Private.CoreLib.dll
----------------------------------------
Kindle Cover Fixer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Kindle%20Cover%20Fixer/Kindle%20Cover%20Fixer.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1823.27201
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1823.27201
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Collections.Specialized.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Collections.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/System.Drawing.Common.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.1823.27201
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.18/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1823.26907
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Numerics.Vectors.dll
----------------------------------------

**Comment by weto91** [comment]
OK, this is a installer error. Give me a few minutos, i will fix it.

**Comment by weto91** [comment]
Ok, try to download version 1.4 again. I have reuploaded the installer.

Before installing, please delete all previous versions of the application in your system to avoid possible conflicts.

Tell me when you try.

Thanks greetings.

**Comment by weto91** [comment]
Only test if the applications opens correctly. Not the error with the Select library button because im fixing it :) i will let you when finish the V1.5 (5-10 mins.)

**Comment by weto91** [comment]
Perfect. You can try with the version 1.5. Same: Uninstall first the old versions that you have installed to avoid possible conflicts.

I hope it works this time! Thanks for your help :)

**Comment by weto91** [comment]
You have the version 1.6. You can test directly this version. I think thats fixes everything, but i have only one computer and i can't test more different environments.. :)

Regards.

**Comment by hideandseekstheorder** [comment]
but in v1.2 its can launch

**Comment by weto91** [comment]
Uhmm, I don't think the problem is due to the hardware you use. It may be due to the version of the operating system. The application should be compatible from Windows 7 (Windows XP is not), but I make system calls that I have only tested in Windows 11, so it is possible that in previous versions they are not done in the same way .

Would it be possible for you to send me an email to: alruad@gmail.com to contact via Whatsapp, Discord or some instant communication application to thoroughly review the problems you have and speed up the process as much as possible?

Thanks greetings.

**Comment by hideandseekstheorder** [comment]
okay i sent u my whatsapp on there

**Comment by weto91** [comment]
I have been testing and it seems that I have managed to fix this error. Can you try it and tell me?

**Comment by hideandseekstheorder** [comment]
Its working now, i am using ur app 2.1 🍎👌⭐⭐
![image](https://github.com/weto91/kindle-cover-fixer/assets/24226435/712ad640-1733-4b61-85b2-e40ddb5ce5f7)
