### ISSUE TITLE
version 2.1 - Just transfer the covers of books in kindle

### ISSUE THREAD

**Issue by CaiZhongheng1987** [weto91/kindle-cover-fixer#7]
I am a kindle scribe user in China, I just used the version 2.1 to fix my book cover and it worked well, thank you very much. However I found that the version 2.1 would transfer all the covers of books in Calibre to my ks with that the books in my ks was just a subset of books in my Calibre library. So the extra book covers was transfered to my kindle.

**Describe the solution you'd like**
Would you like to check the book's names in kindle and select the counterpart covers in version 2.1 to transfer to the kindle? So the extra covers will disappear. Thank you very much.

**Comment by weto91** [comment]
Hi, thanks for the comment!
Indeed, this is in the process of development, in the next few days we will upload the version with this change.

thanks for the warning!

**Comment by weto91** [comment]
Hello friend!,

I just released version 2.2, which includes the function you requested as well as many others. Try it, see what you think.

All the best. 😄

**Comment by CaiZhongheng1987** [comment]
I am very sorry to report you the fail of use the verison>2.1.
When I use 2.2 and above version to generate the covers of books in Calibre library, the kindle-cover-fix would crash. But verion 2.1 would work and generate covers.

**Comment by weto91** [comment]
Hello again, can yo attach the log file? it was generated on %APPDATA%/Kindle Cover Fixer/Log

Thanks!

**Comment by CaiZhongheng1987** [comment]
No problem.

This is the log file. Hope it to help you.
[Kindle_Cover_Fixer.log](https://github.com/weto91/kindle-cover-fixer/files/13467309/Kindle_Cover_Fixer.log)

**Comment by CaiZhongheng1987** [comment]
And , verison 2.4 producted some covers and crashed by one book.

![image](https://github.com/weto91/kindle-cover-fixer/assets/38467143/940d0931-d25b-414f-8914-4feacf6e62fa)

**Comment by weto91** [comment]
I can see in the metadata calibre file, that you have some books without UUID... Kindle identify the cover by the UUID (As you can see in the images "thumbnail_" + UUID + "_EBOK_Portrait.jpg"

Please, try to:

1. Open calibre
2. Select all books
3. Convert all books in another format
4. Delete the old format
5. Convert again all books to the old format
6. Send the Books to your Kindle again
7. Run Kindle Cover Fixer and try again to fix the Covers.

Take into account, this aplication cant work without UUID.. is the main data to make the application work.. Without it.. Nothing happen...
